// Code generated by ent, DO NOT EDIT.

package plugin

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/flowline-io/flowbot-registry/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldID, id))
}

// NamespaceID applies equality check predicate on the "namespace_id" field. It's identical to NamespaceIDEQ.
func NamespaceID(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldNamespaceID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDisplayName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDescription, v))
}

// LogoURL applies equality check predicate on the "logo_url" field. It's identical to LogoURLEQ.
func LogoURL(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLogoURL, v))
}

// NamespaceIDEQ applies the EQ predicate on the "namespace_id" field.
func NamespaceIDEQ(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldNamespaceID, v))
}

// NamespaceIDNEQ applies the NEQ predicate on the "namespace_id" field.
func NamespaceIDNEQ(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldNamespaceID, v))
}

// NamespaceIDIn applies the In predicate on the "namespace_id" field.
func NamespaceIDIn(vs ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldNamespaceID, vs...))
}

// NamespaceIDNotIn applies the NotIn predicate on the "namespace_id" field.
func NamespaceIDNotIn(vs ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldNamespaceID, vs...))
}

// NamespaceIDGT applies the GT predicate on the "namespace_id" field.
func NamespaceIDGT(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldNamespaceID, v))
}

// NamespaceIDGTE applies the GTE predicate on the "namespace_id" field.
func NamespaceIDGTE(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldNamespaceID, v))
}

// NamespaceIDLT applies the LT predicate on the "namespace_id" field.
func NamespaceIDLT(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldNamespaceID, v))
}

// NamespaceIDLTE applies the LTE predicate on the "namespace_id" field.
func NamespaceIDLTE(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldNamespaceID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldDisplayName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldDescription, v))
}

// LogoURLEQ applies the EQ predicate on the "logo_url" field.
func LogoURLEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLogoURL, v))
}

// LogoURLNEQ applies the NEQ predicate on the "logo_url" field.
func LogoURLNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldLogoURL, v))
}

// LogoURLIn applies the In predicate on the "logo_url" field.
func LogoURLIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldLogoURL, vs...))
}

// LogoURLNotIn applies the NotIn predicate on the "logo_url" field.
func LogoURLNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldLogoURL, vs...))
}

// LogoURLGT applies the GT predicate on the "logo_url" field.
func LogoURLGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldLogoURL, v))
}

// LogoURLGTE applies the GTE predicate on the "logo_url" field.
func LogoURLGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldLogoURL, v))
}

// LogoURLLT applies the LT predicate on the "logo_url" field.
func LogoURLLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldLogoURL, v))
}

// LogoURLLTE applies the LTE predicate on the "logo_url" field.
func LogoURLLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldLogoURL, v))
}

// LogoURLContains applies the Contains predicate on the "logo_url" field.
func LogoURLContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldLogoURL, v))
}

// LogoURLHasPrefix applies the HasPrefix predicate on the "logo_url" field.
func LogoURLHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldLogoURL, v))
}

// LogoURLHasSuffix applies the HasSuffix predicate on the "logo_url" field.
func LogoURLHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldLogoURL, v))
}

// LogoURLEqualFold applies the EqualFold predicate on the "logo_url" field.
func LogoURLEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldLogoURL, v))
}

// LogoURLContainsFold applies the ContainsFold predicate on the "logo_url" field.
func LogoURLContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldLogoURL, v))
}

// HasVersions applies the HasEdge predicate on the "versions" edge.
func HasVersions() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionsWith applies the HasEdge predicate on the "versions" edge with a given conditions (other predicates).
func HasVersionsWith(preds ...predicate.PluginVersion) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.NotPredicates(p))
}
