// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NamespacesColumns holds the columns for the "namespaces" table.
	NamespacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "user_namespaces", Type: field.TypeInt, Nullable: true},
	}
	// NamespacesTable holds the schema information for the "namespaces" table.
	NamespacesTable = &schema.Table{
		Name:       "namespaces",
		Columns:    NamespacesColumns,
		PrimaryKey: []*schema.Column{NamespacesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "namespaces_users_namespaces",
				Columns:    []*schema.Column{NamespacesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PluginsColumns holds the columns for the "plugins" table.
	PluginsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "namespace_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "logo_url", Type: field.TypeString, Default: ""},
		{Name: "namespace_plugins", Type: field.TypeInt, Nullable: true},
	}
	// PluginsTable holds the schema information for the "plugins" table.
	PluginsTable = &schema.Table{
		Name:       "plugins",
		Columns:    PluginsColumns,
		PrimaryKey: []*schema.Column{PluginsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "plugins_namespaces_plugins",
				Columns:    []*schema.Column{PluginsColumns[6]},
				RefColumns: []*schema.Column{NamespacesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "plugin_namespace_id_name",
				Unique:  true,
				Columns: []*schema.Column{PluginsColumns[1], PluginsColumns[2]},
			},
		},
	}
	// PluginVersionsColumns holds the columns for the "plugin_versions" table.
	PluginVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeString},
		{Name: "oci_image_ref", Type: field.TypeString, Default: ""},
		{Name: "oci_digest", Type: field.TypeString},
		{Name: "readme_html", Type: field.TypeString, Default: ""},
		{Name: "manifest_json", Type: field.TypeJSON},
		{Name: "plugin_id", Type: field.TypeInt},
	}
	// PluginVersionsTable holds the schema information for the "plugin_versions" table.
	PluginVersionsTable = &schema.Table{
		Name:       "plugin_versions",
		Columns:    PluginVersionsColumns,
		PrimaryKey: []*schema.Column{PluginVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "plugin_versions_plugins_versions",
				Columns:    []*schema.Column{PluginVersionsColumns[6]},
				RefColumns: []*schema.Column{PluginsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pluginversion_plugin_id_version",
				Unique:  true,
				Columns: []*schema.Column{PluginVersionsColumns[6], PluginVersionsColumns[1]},
			},
		},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_refresh_tokens", Type: field.TypeInt, Nullable: true},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_tokens_users_refresh_tokens",
				Columns:    []*schema.Column{RefreshTokensColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NamespacesTable,
		PluginsTable,
		PluginVersionsTable,
		RefreshTokensTable,
		UsersTable,
	}
)

func init() {
	NamespacesTable.ForeignKeys[0].RefTable = UsersTable
	PluginsTable.ForeignKeys[0].RefTable = NamespacesTable
	PluginVersionsTable.ForeignKeys[0].RefTable = PluginsTable
	RefreshTokensTable.ForeignKeys[0].RefTable = UsersTable
}
