// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NamespacesColumns holds the columns for the "namespaces" table.
	NamespacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
	}
	// NamespacesTable holds the schema information for the "namespaces" table.
	NamespacesTable = &schema.Table{
		Name:       "namespaces",
		Columns:    NamespacesColumns,
		PrimaryKey: []*schema.Column{NamespacesColumns[0]},
	}
	// PluginsColumns holds the columns for the "plugins" table.
	PluginsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "namespace_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "logo_url", Type: field.TypeString, Default: ""},
		{Name: "namespace_plugins", Type: field.TypeInt, Nullable: true},
	}
	// PluginsTable holds the schema information for the "plugins" table.
	PluginsTable = &schema.Table{
		Name:       "plugins",
		Columns:    PluginsColumns,
		PrimaryKey: []*schema.Column{PluginsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "plugins_namespaces_plugins",
				Columns:    []*schema.Column{PluginsColumns[6]},
				RefColumns: []*schema.Column{NamespacesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "plugin_namespace_id_name",
				Unique:  true,
				Columns: []*schema.Column{PluginsColumns[1], PluginsColumns[2]},
			},
		},
	}
	// PluginVersionsColumns holds the columns for the "plugin_versions" table.
	PluginVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeString},
		{Name: "oci_image_ref", Type: field.TypeString, Default: ""},
		{Name: "oci_digest", Type: field.TypeString},
		{Name: "readme_html", Type: field.TypeString, Default: ""},
		{Name: "manifest_json", Type: field.TypeJSON},
		{Name: "plugin_id", Type: field.TypeInt},
	}
	// PluginVersionsTable holds the schema information for the "plugin_versions" table.
	PluginVersionsTable = &schema.Table{
		Name:       "plugin_versions",
		Columns:    PluginVersionsColumns,
		PrimaryKey: []*schema.Column{PluginVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "plugin_versions_plugins_versions",
				Columns:    []*schema.Column{PluginVersionsColumns[6]},
				RefColumns: []*schema.Column{PluginsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pluginversion_plugin_id_version",
				Unique:  true,
				Columns: []*schema.Column{PluginVersionsColumns[6], PluginVersionsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NamespacesTable,
		PluginsTable,
		PluginVersionsTable,
	}
)

func init() {
	PluginsTable.ForeignKeys[0].RefTable = NamespacesTable
	PluginVersionsTable.ForeignKeys[0].RefTable = PluginsTable
}
