// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flowline-io/flowbot-registry/internal/ent/namespace"
	"github.com/flowline-io/flowbot-registry/internal/ent/plugin"
	"github.com/flowline-io/flowbot-registry/internal/ent/predicate"
)

// NamespaceUpdate is the builder for updating Namespace entities.
type NamespaceUpdate struct {
	config
	hooks    []Hook
	mutation *NamespaceMutation
}

// Where appends a list predicates to the NamespaceUpdate builder.
func (_u *NamespaceUpdate) Where(ps ...predicate.Namespace) *NamespaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NamespaceUpdate) SetName(v string) *NamespaceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NamespaceUpdate) SetNillableName(v *string) *NamespaceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *NamespaceUpdate) SetType(v string) *NamespaceUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NamespaceUpdate) SetNillableType(v *string) *NamespaceUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddPluginIDs adds the "plugins" edge to the Plugin entity by IDs.
func (_u *NamespaceUpdate) AddPluginIDs(ids ...int) *NamespaceUpdate {
	_u.mutation.AddPluginIDs(ids...)
	return _u
}

// AddPlugins adds the "plugins" edges to the Plugin entity.
func (_u *NamespaceUpdate) AddPlugins(v ...*Plugin) *NamespaceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPluginIDs(ids...)
}

// Mutation returns the NamespaceMutation object of the builder.
func (_u *NamespaceUpdate) Mutation() *NamespaceMutation {
	return _u.mutation
}

// ClearPlugins clears all "plugins" edges to the Plugin entity.
func (_u *NamespaceUpdate) ClearPlugins() *NamespaceUpdate {
	_u.mutation.ClearPlugins()
	return _u
}

// RemovePluginIDs removes the "plugins" edge to Plugin entities by IDs.
func (_u *NamespaceUpdate) RemovePluginIDs(ids ...int) *NamespaceUpdate {
	_u.mutation.RemovePluginIDs(ids...)
	return _u
}

// RemovePlugins removes "plugins" edges to Plugin entities.
func (_u *NamespaceUpdate) RemovePlugins(v ...*Plugin) *NamespaceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePluginIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NamespaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NamespaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NamespaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NamespaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NamespaceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := namespace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Namespace.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := namespace.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Namespace.type": %w`, err)}
		}
	}
	return nil
}

func (_u *NamespaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(namespace.Table, namespace.Columns, sqlgraph.NewFieldSpec(namespace.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(namespace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(namespace.FieldType, field.TypeString, value)
	}
	if _u.mutation.PluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   namespace.PluginsTable,
			Columns: []string{namespace.PluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPluginsIDs(); len(nodes) > 0 && !_u.mutation.PluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   namespace.PluginsTable,
			Columns: []string{namespace.PluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   namespace.PluginsTable,
			Columns: []string{namespace.PluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{namespace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NamespaceUpdateOne is the builder for updating a single Namespace entity.
type NamespaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NamespaceMutation
}

// SetName sets the "name" field.
func (_u *NamespaceUpdateOne) SetName(v string) *NamespaceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NamespaceUpdateOne) SetNillableName(v *string) *NamespaceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *NamespaceUpdateOne) SetType(v string) *NamespaceUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NamespaceUpdateOne) SetNillableType(v *string) *NamespaceUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddPluginIDs adds the "plugins" edge to the Plugin entity by IDs.
func (_u *NamespaceUpdateOne) AddPluginIDs(ids ...int) *NamespaceUpdateOne {
	_u.mutation.AddPluginIDs(ids...)
	return _u
}

// AddPlugins adds the "plugins" edges to the Plugin entity.
func (_u *NamespaceUpdateOne) AddPlugins(v ...*Plugin) *NamespaceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPluginIDs(ids...)
}

// Mutation returns the NamespaceMutation object of the builder.
func (_u *NamespaceUpdateOne) Mutation() *NamespaceMutation {
	return _u.mutation
}

// ClearPlugins clears all "plugins" edges to the Plugin entity.
func (_u *NamespaceUpdateOne) ClearPlugins() *NamespaceUpdateOne {
	_u.mutation.ClearPlugins()
	return _u
}

// RemovePluginIDs removes the "plugins" edge to Plugin entities by IDs.
func (_u *NamespaceUpdateOne) RemovePluginIDs(ids ...int) *NamespaceUpdateOne {
	_u.mutation.RemovePluginIDs(ids...)
	return _u
}

// RemovePlugins removes "plugins" edges to Plugin entities.
func (_u *NamespaceUpdateOne) RemovePlugins(v ...*Plugin) *NamespaceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePluginIDs(ids...)
}

// Where appends a list predicates to the NamespaceUpdate builder.
func (_u *NamespaceUpdateOne) Where(ps ...predicate.Namespace) *NamespaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NamespaceUpdateOne) Select(field string, fields ...string) *NamespaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Namespace entity.
func (_u *NamespaceUpdateOne) Save(ctx context.Context) (*Namespace, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NamespaceUpdateOne) SaveX(ctx context.Context) *Namespace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NamespaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NamespaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NamespaceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := namespace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Namespace.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := namespace.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Namespace.type": %w`, err)}
		}
	}
	return nil
}

func (_u *NamespaceUpdateOne) sqlSave(ctx context.Context) (_node *Namespace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(namespace.Table, namespace.Columns, sqlgraph.NewFieldSpec(namespace.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Namespace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, namespace.FieldID)
		for _, f := range fields {
			if !namespace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != namespace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(namespace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(namespace.FieldType, field.TypeString, value)
	}
	if _u.mutation.PluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   namespace.PluginsTable,
			Columns: []string{namespace.PluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPluginsIDs(); len(nodes) > 0 && !_u.mutation.PluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   namespace.PluginsTable,
			Columns: []string{namespace.PluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   namespace.PluginsTable,
			Columns: []string{namespace.PluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Namespace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{namespace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
