// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flowline-io/flowbot-registry/internal/ent/plugin"
	"github.com/flowline-io/flowbot-registry/internal/ent/pluginversion"
)

// PluginVersion is the model entity for the PluginVersion schema.
type PluginVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PluginID holds the value of the "plugin_id" field.
	PluginID int `json:"plugin_id,omitempty"`
	// semver
	Version string `json:"version,omitempty"`
	// OCI repository reference
	OciImageRef string `json:"oci_image_ref,omitempty"`
	// SHA256 digest
	OciDigest string `json:"oci_digest,omitempty"`
	// ReadmeHTML holds the value of the "readme_html" field.
	ReadmeHTML string `json:"readme_html,omitempty"`
	// ManifestJSON holds the value of the "manifest_json" field.
	ManifestJSON map[string]interface{} `json:"manifest_json,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PluginVersionQuery when eager-loading is set.
	Edges        PluginVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PluginVersionEdges holds the relations/edges for other nodes in the graph.
type PluginVersionEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PluginVersionEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pluginversion.FieldManifestJSON:
			values[i] = new([]byte)
		case pluginversion.FieldID, pluginversion.FieldPluginID:
			values[i] = new(sql.NullInt64)
		case pluginversion.FieldVersion, pluginversion.FieldOciImageRef, pluginversion.FieldOciDigest, pluginversion.FieldReadmeHTML:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginVersion fields.
func (_m *PluginVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pluginversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pluginversion.FieldPluginID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value.Valid {
				_m.PluginID = int(value.Int64)
			}
		case pluginversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case pluginversion.FieldOciImageRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oci_image_ref", values[i])
			} else if value.Valid {
				_m.OciImageRef = value.String
			}
		case pluginversion.FieldOciDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oci_digest", values[i])
			} else if value.Valid {
				_m.OciDigest = value.String
			}
		case pluginversion.FieldReadmeHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field readme_html", values[i])
			} else if value.Valid {
				_m.ReadmeHTML = value.String
			}
		case pluginversion.FieldManifestJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field manifest_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ManifestJSON); err != nil {
					return fmt.Errorf("unmarshal field manifest_json: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PluginVersion.
// This includes values selected through modifiers, order, etc.
func (_m *PluginVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugin queries the "plugin" edge of the PluginVersion entity.
func (_m *PluginVersion) QueryPlugin() *PluginQuery {
	return NewPluginVersionClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this PluginVersion.
// Note that you need to call PluginVersion.Unwrap() before calling this method if this PluginVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PluginVersion) Update() *PluginVersionUpdateOne {
	return NewPluginVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PluginVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PluginVersion) Unwrap() *PluginVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PluginVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PluginVersion) String() string {
	var builder strings.Builder
	builder.WriteString("PluginVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plugin_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PluginID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("oci_image_ref=")
	builder.WriteString(_m.OciImageRef)
	builder.WriteString(", ")
	builder.WriteString("oci_digest=")
	builder.WriteString(_m.OciDigest)
	builder.WriteString(", ")
	builder.WriteString("readme_html=")
	builder.WriteString(_m.ReadmeHTML)
	builder.WriteString(", ")
	builder.WriteString("manifest_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManifestJSON))
	builder.WriteByte(')')
	return builder.String()
}

// PluginVersions is a parsable slice of PluginVersion.
type PluginVersions []*PluginVersion
