// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flowline-io/flowbot-registry/internal/ent/plugin"
	"github.com/flowline-io/flowbot-registry/internal/ent/pluginversion"
	"github.com/flowline-io/flowbot-registry/internal/ent/predicate"
)

// PluginVersionUpdate is the builder for updating PluginVersion entities.
type PluginVersionUpdate struct {
	config
	hooks    []Hook
	mutation *PluginVersionMutation
}

// Where appends a list predicates to the PluginVersionUpdate builder.
func (_u *PluginVersionUpdate) Where(ps ...predicate.PluginVersion) *PluginVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginVersionUpdate) SetPluginID(v int) *PluginVersionUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillablePluginID(v *int) *PluginVersionUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PluginVersionUpdate) SetVersion(v string) *PluginVersionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableVersion(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetOciImageRef sets the "oci_image_ref" field.
func (_u *PluginVersionUpdate) SetOciImageRef(v string) *PluginVersionUpdate {
	_u.mutation.SetOciImageRef(v)
	return _u
}

// SetNillableOciImageRef sets the "oci_image_ref" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableOciImageRef(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetOciImageRef(*v)
	}
	return _u
}

// SetOciDigest sets the "oci_digest" field.
func (_u *PluginVersionUpdate) SetOciDigest(v string) *PluginVersionUpdate {
	_u.mutation.SetOciDigest(v)
	return _u
}

// SetNillableOciDigest sets the "oci_digest" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableOciDigest(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetOciDigest(*v)
	}
	return _u
}

// SetReadmeHTML sets the "readme_html" field.
func (_u *PluginVersionUpdate) SetReadmeHTML(v string) *PluginVersionUpdate {
	_u.mutation.SetReadmeHTML(v)
	return _u
}

// SetNillableReadmeHTML sets the "readme_html" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableReadmeHTML(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetReadmeHTML(*v)
	}
	return _u
}

// SetManifestJSON sets the "manifest_json" field.
func (_u *PluginVersionUpdate) SetManifestJSON(v map[string]interface{}) *PluginVersionUpdate {
	_u.mutation.SetManifestJSON(v)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *PluginVersionUpdate) SetPlugin(v *Plugin) *PluginVersionUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the PluginVersionMutation object of the builder.
func (_u *PluginVersionUpdate) Mutation() *PluginVersionMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *PluginVersionUpdate) ClearPlugin() *PluginVersionUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginVersionUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := pluginversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OciDigest(); ok {
		if err := pluginversion.OciDigestValidator(v); err != nil {
			return &ValidationError{Name: "oci_digest", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.oci_digest": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginVersion.plugin"`)
	}
	return nil
}

func (_u *PluginVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginversion.Table, pluginversion.Columns, sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(pluginversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.OciImageRef(); ok {
		_spec.SetField(pluginversion.FieldOciImageRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.OciDigest(); ok {
		_spec.SetField(pluginversion.FieldOciDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadmeHTML(); ok {
		_spec.SetField(pluginversion.FieldReadmeHTML, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManifestJSON(); ok {
		_spec.SetField(pluginversion.FieldManifestJSON, field.TypeJSON, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginVersionUpdateOne is the builder for updating a single PluginVersion entity.
type PluginVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginVersionMutation
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginVersionUpdateOne) SetPluginID(v int) *PluginVersionUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillablePluginID(v *int) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PluginVersionUpdateOne) SetVersion(v string) *PluginVersionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableVersion(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetOciImageRef sets the "oci_image_ref" field.
func (_u *PluginVersionUpdateOne) SetOciImageRef(v string) *PluginVersionUpdateOne {
	_u.mutation.SetOciImageRef(v)
	return _u
}

// SetNillableOciImageRef sets the "oci_image_ref" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableOciImageRef(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetOciImageRef(*v)
	}
	return _u
}

// SetOciDigest sets the "oci_digest" field.
func (_u *PluginVersionUpdateOne) SetOciDigest(v string) *PluginVersionUpdateOne {
	_u.mutation.SetOciDigest(v)
	return _u
}

// SetNillableOciDigest sets the "oci_digest" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableOciDigest(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetOciDigest(*v)
	}
	return _u
}

// SetReadmeHTML sets the "readme_html" field.
func (_u *PluginVersionUpdateOne) SetReadmeHTML(v string) *PluginVersionUpdateOne {
	_u.mutation.SetReadmeHTML(v)
	return _u
}

// SetNillableReadmeHTML sets the "readme_html" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableReadmeHTML(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetReadmeHTML(*v)
	}
	return _u
}

// SetManifestJSON sets the "manifest_json" field.
func (_u *PluginVersionUpdateOne) SetManifestJSON(v map[string]interface{}) *PluginVersionUpdateOne {
	_u.mutation.SetManifestJSON(v)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *PluginVersionUpdateOne) SetPlugin(v *Plugin) *PluginVersionUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the PluginVersionMutation object of the builder.
func (_u *PluginVersionUpdateOne) Mutation() *PluginVersionMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *PluginVersionUpdateOne) ClearPlugin() *PluginVersionUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the PluginVersionUpdate builder.
func (_u *PluginVersionUpdateOne) Where(ps ...predicate.PluginVersion) *PluginVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginVersionUpdateOne) Select(field string, fields ...string) *PluginVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PluginVersion entity.
func (_u *PluginVersionUpdateOne) Save(ctx context.Context) (*PluginVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginVersionUpdateOne) SaveX(ctx context.Context) *PluginVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := pluginversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OciDigest(); ok {
		if err := pluginversion.OciDigestValidator(v); err != nil {
			return &ValidationError{Name: "oci_digest", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.oci_digest": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginVersion.plugin"`)
	}
	return nil
}

func (_u *PluginVersionUpdateOne) sqlSave(ctx context.Context) (_node *PluginVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginversion.Table, pluginversion.Columns, sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginversion.FieldID)
		for _, f := range fields {
			if !pluginversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(pluginversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.OciImageRef(); ok {
		_spec.SetField(pluginversion.FieldOciImageRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.OciDigest(); ok {
		_spec.SetField(pluginversion.FieldOciDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadmeHTML(); ok {
		_spec.SetField(pluginversion.FieldReadmeHTML, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManifestJSON(); ok {
		_spec.SetField(pluginversion.FieldManifestJSON, field.TypeJSON, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PluginVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
