// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flowline-io/flowbot-registry/internal/ent/plugin"
	"github.com/flowline-io/flowbot-registry/internal/ent/pluginversion"
)

// PluginVersionCreate is the builder for creating a PluginVersion entity.
type PluginVersionCreate struct {
	config
	mutation *PluginVersionMutation
	hooks    []Hook
}

// SetPluginID sets the "plugin_id" field.
func (_c *PluginVersionCreate) SetPluginID(v int) *PluginVersionCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *PluginVersionCreate) SetVersion(v string) *PluginVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetOciImageRef sets the "oci_image_ref" field.
func (_c *PluginVersionCreate) SetOciImageRef(v string) *PluginVersionCreate {
	_c.mutation.SetOciImageRef(v)
	return _c
}

// SetNillableOciImageRef sets the "oci_image_ref" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableOciImageRef(v *string) *PluginVersionCreate {
	if v != nil {
		_c.SetOciImageRef(*v)
	}
	return _c
}

// SetOciDigest sets the "oci_digest" field.
func (_c *PluginVersionCreate) SetOciDigest(v string) *PluginVersionCreate {
	_c.mutation.SetOciDigest(v)
	return _c
}

// SetReadmeHTML sets the "readme_html" field.
func (_c *PluginVersionCreate) SetReadmeHTML(v string) *PluginVersionCreate {
	_c.mutation.SetReadmeHTML(v)
	return _c
}

// SetNillableReadmeHTML sets the "readme_html" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableReadmeHTML(v *string) *PluginVersionCreate {
	if v != nil {
		_c.SetReadmeHTML(*v)
	}
	return _c
}

// SetManifestJSON sets the "manifest_json" field.
func (_c *PluginVersionCreate) SetManifestJSON(v map[string]interface{}) *PluginVersionCreate {
	_c.mutation.SetManifestJSON(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PluginVersionCreate) SetID(v int) *PluginVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_c *PluginVersionCreate) SetPlugin(v *Plugin) *PluginVersionCreate {
	return _c.SetPluginID(v.ID)
}

// Mutation returns the PluginVersionMutation object of the builder.
func (_c *PluginVersionCreate) Mutation() *PluginVersionMutation {
	return _c.mutation
}

// Save creates the PluginVersion in the database.
func (_c *PluginVersionCreate) Save(ctx context.Context) (*PluginVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginVersionCreate) SaveX(ctx context.Context) *PluginVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginVersionCreate) defaults() {
	if _, ok := _c.mutation.OciImageRef(); !ok {
		v := pluginversion.DefaultOciImageRef
		_c.mutation.SetOciImageRef(v)
	}
	if _, ok := _c.mutation.ReadmeHTML(); !ok {
		v := pluginversion.DefaultReadmeHTML
		_c.mutation.SetReadmeHTML(v)
	}
	if _, ok := _c.mutation.ManifestJSON(); !ok {
		v := pluginversion.DefaultManifestJSON
		_c.mutation.SetManifestJSON(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginVersionCreate) check() error {
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "PluginVersion.plugin_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "PluginVersion.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := pluginversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OciImageRef(); !ok {
		return &ValidationError{Name: "oci_image_ref", err: errors.New(`ent: missing required field "PluginVersion.oci_image_ref"`)}
	}
	if _, ok := _c.mutation.OciDigest(); !ok {
		return &ValidationError{Name: "oci_digest", err: errors.New(`ent: missing required field "PluginVersion.oci_digest"`)}
	}
	if v, ok := _c.mutation.OciDigest(); ok {
		if err := pluginversion.OciDigestValidator(v); err != nil {
			return &ValidationError{Name: "oci_digest", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.oci_digest": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReadmeHTML(); !ok {
		return &ValidationError{Name: "readme_html", err: errors.New(`ent: missing required field "PluginVersion.readme_html"`)}
	}
	if _, ok := _c.mutation.ManifestJSON(); !ok {
		return &ValidationError{Name: "manifest_json", err: errors.New(`ent: missing required field "PluginVersion.manifest_json"`)}
	}
	if len(_c.mutation.PluginIDs()) == 0 {
		return &ValidationError{Name: "plugin", err: errors.New(`ent: missing required edge "PluginVersion.plugin"`)}
	}
	return nil
}

func (_c *PluginVersionCreate) sqlSave(ctx context.Context) (*PluginVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginVersionCreate) createSpec() (*PluginVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pluginversion.Table, sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(pluginversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.OciImageRef(); ok {
		_spec.SetField(pluginversion.FieldOciImageRef, field.TypeString, value)
		_node.OciImageRef = value
	}
	if value, ok := _c.mutation.OciDigest(); ok {
		_spec.SetField(pluginversion.FieldOciDigest, field.TypeString, value)
		_node.OciDigest = value
	}
	if value, ok := _c.mutation.ReadmeHTML(); ok {
		_spec.SetField(pluginversion.FieldReadmeHTML, field.TypeString, value)
		_node.ReadmeHTML = value
	}
	if value, ok := _c.mutation.ManifestJSON(); ok {
		_spec.SetField(pluginversion.FieldManifestJSON, field.TypeJSON, value)
		_node.ManifestJSON = value
	}
	if nodes := _c.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PluginID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PluginVersionCreateBulk is the builder for creating many PluginVersion entities in bulk.
type PluginVersionCreateBulk struct {
	config
	err      error
	builders []*PluginVersionCreate
}

// Save creates the PluginVersion entities in the database.
func (_c *PluginVersionCreateBulk) Save(ctx context.Context) ([]*PluginVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginVersionCreateBulk) SaveX(ctx context.Context) []*PluginVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
