// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/flowline-io/flowbot-registry/internal/ent/namespace"
	"github.com/flowline-io/flowbot-registry/internal/ent/plugin"
	"github.com/flowline-io/flowbot-registry/internal/ent/pluginversion"
	"github.com/flowline-io/flowbot-registry/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	namespaceFields := schema.Namespace{}.Fields()
	_ = namespaceFields
	// namespaceDescName is the schema descriptor for name field.
	namespaceDescName := namespaceFields[1].Descriptor()
	// namespace.NameValidator is a validator for the "name" field. It is called by the builders before save.
	namespace.NameValidator = namespaceDescName.Validators[0].(func(string) error)
	// namespaceDescType is the schema descriptor for type field.
	namespaceDescType := namespaceFields[2].Descriptor()
	// namespace.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	namespace.TypeValidator = namespaceDescType.Validators[0].(func(string) error)
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescName is the schema descriptor for name field.
	pluginDescName := pluginFields[2].Descriptor()
	// plugin.NameValidator is a validator for the "name" field. It is called by the builders before save.
	plugin.NameValidator = pluginDescName.Validators[0].(func(string) error)
	// pluginDescDisplayName is the schema descriptor for display_name field.
	pluginDescDisplayName := pluginFields[3].Descriptor()
	// plugin.DefaultDisplayName holds the default value on creation for the display_name field.
	plugin.DefaultDisplayName = pluginDescDisplayName.Default.(string)
	// pluginDescDescription is the schema descriptor for description field.
	pluginDescDescription := pluginFields[4].Descriptor()
	// plugin.DefaultDescription holds the default value on creation for the description field.
	plugin.DefaultDescription = pluginDescDescription.Default.(string)
	// pluginDescLogoURL is the schema descriptor for logo_url field.
	pluginDescLogoURL := pluginFields[5].Descriptor()
	// plugin.DefaultLogoURL holds the default value on creation for the logo_url field.
	plugin.DefaultLogoURL = pluginDescLogoURL.Default.(string)
	pluginversionFields := schema.PluginVersion{}.Fields()
	_ = pluginversionFields
	// pluginversionDescVersion is the schema descriptor for version field.
	pluginversionDescVersion := pluginversionFields[2].Descriptor()
	// pluginversion.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	pluginversion.VersionValidator = pluginversionDescVersion.Validators[0].(func(string) error)
	// pluginversionDescOciImageRef is the schema descriptor for oci_image_ref field.
	pluginversionDescOciImageRef := pluginversionFields[3].Descriptor()
	// pluginversion.DefaultOciImageRef holds the default value on creation for the oci_image_ref field.
	pluginversion.DefaultOciImageRef = pluginversionDescOciImageRef.Default.(string)
	// pluginversionDescOciDigest is the schema descriptor for oci_digest field.
	pluginversionDescOciDigest := pluginversionFields[4].Descriptor()
	// pluginversion.OciDigestValidator is a validator for the "oci_digest" field. It is called by the builders before save.
	pluginversion.OciDigestValidator = pluginversionDescOciDigest.Validators[0].(func(string) error)
	// pluginversionDescReadmeHTML is the schema descriptor for readme_html field.
	pluginversionDescReadmeHTML := pluginversionFields[5].Descriptor()
	// pluginversion.DefaultReadmeHTML holds the default value on creation for the readme_html field.
	pluginversion.DefaultReadmeHTML = pluginversionDescReadmeHTML.Default.(string)
	// pluginversionDescManifestJSON is the schema descriptor for manifest_json field.
	pluginversionDescManifestJSON := pluginversionFields[6].Descriptor()
	// pluginversion.DefaultManifestJSON holds the default value on creation for the manifest_json field.
	pluginversion.DefaultManifestJSON = pluginversionDescManifestJSON.Default.(map[string]interface{})
}
