// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/flowline-io/flowbot-registry/internal/ent/namespace"
	"github.com/flowline-io/flowbot-registry/internal/ent/plugin"
	"github.com/flowline-io/flowbot-registry/internal/ent/pluginversion"
	"github.com/flowline-io/flowbot-registry/internal/ent/refreshtoken"
	"github.com/flowline-io/flowbot-registry/internal/ent/schema"
	"github.com/flowline-io/flowbot-registry/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	namespaceFields := schema.Namespace{}.Fields()
	_ = namespaceFields
	// namespaceDescName is the schema descriptor for name field.
	namespaceDescName := namespaceFields[1].Descriptor()
	// namespace.NameValidator is a validator for the "name" field. It is called by the builders before save.
	namespace.NameValidator = namespaceDescName.Validators[0].(func(string) error)
	// namespaceDescType is the schema descriptor for type field.
	namespaceDescType := namespaceFields[2].Descriptor()
	// namespace.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	namespace.TypeValidator = namespaceDescType.Validators[0].(func(string) error)
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescName is the schema descriptor for name field.
	pluginDescName := pluginFields[2].Descriptor()
	// plugin.NameValidator is a validator for the "name" field. It is called by the builders before save.
	plugin.NameValidator = pluginDescName.Validators[0].(func(string) error)
	// pluginDescDisplayName is the schema descriptor for display_name field.
	pluginDescDisplayName := pluginFields[3].Descriptor()
	// plugin.DefaultDisplayName holds the default value on creation for the display_name field.
	plugin.DefaultDisplayName = pluginDescDisplayName.Default.(string)
	// pluginDescDescription is the schema descriptor for description field.
	pluginDescDescription := pluginFields[4].Descriptor()
	// plugin.DefaultDescription holds the default value on creation for the description field.
	plugin.DefaultDescription = pluginDescDescription.Default.(string)
	// pluginDescLogoURL is the schema descriptor for logo_url field.
	pluginDescLogoURL := pluginFields[5].Descriptor()
	// plugin.DefaultLogoURL holds the default value on creation for the logo_url field.
	plugin.DefaultLogoURL = pluginDescLogoURL.Default.(string)
	pluginversionFields := schema.PluginVersion{}.Fields()
	_ = pluginversionFields
	// pluginversionDescVersion is the schema descriptor for version field.
	pluginversionDescVersion := pluginversionFields[2].Descriptor()
	// pluginversion.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	pluginversion.VersionValidator = pluginversionDescVersion.Validators[0].(func(string) error)
	// pluginversionDescOciImageRef is the schema descriptor for oci_image_ref field.
	pluginversionDescOciImageRef := pluginversionFields[3].Descriptor()
	// pluginversion.DefaultOciImageRef holds the default value on creation for the oci_image_ref field.
	pluginversion.DefaultOciImageRef = pluginversionDescOciImageRef.Default.(string)
	// pluginversionDescOciDigest is the schema descriptor for oci_digest field.
	pluginversionDescOciDigest := pluginversionFields[4].Descriptor()
	// pluginversion.OciDigestValidator is a validator for the "oci_digest" field. It is called by the builders before save.
	pluginversion.OciDigestValidator = pluginversionDescOciDigest.Validators[0].(func(string) error)
	// pluginversionDescReadmeHTML is the schema descriptor for readme_html field.
	pluginversionDescReadmeHTML := pluginversionFields[5].Descriptor()
	// pluginversion.DefaultReadmeHTML holds the default value on creation for the readme_html field.
	pluginversion.DefaultReadmeHTML = pluginversionDescReadmeHTML.Default.(string)
	// pluginversionDescManifestJSON is the schema descriptor for manifest_json field.
	pluginversionDescManifestJSON := pluginversionFields[6].Descriptor()
	// pluginversion.DefaultManifestJSON holds the default value on creation for the manifest_json field.
	pluginversion.DefaultManifestJSON = pluginversionDescManifestJSON.Default.(map[string]interface{})
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescToken is the schema descriptor for token field.
	refreshtokenDescToken := refreshtokenFields[1].Descriptor()
	// refreshtoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	refreshtoken.TokenValidator = refreshtokenDescToken.Validators[0].(func(string) error)
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[3].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
