// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Namespace is the predicate function for namespace builders.
type Namespace func(*sql.Selector)

// Plugin is the predicate function for plugin builders.
type Plugin func(*sql.Selector)

// PluginVersion is the predicate function for pluginversion builders.
type PluginVersion func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
