// Code generated by ent, DO NOT EDIT.

package pluginversion

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pluginversion type in the database.
	Label = "plugin_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPluginID holds the string denoting the plugin_id field in the database.
	FieldPluginID = "plugin_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldOciImageRef holds the string denoting the oci_image_ref field in the database.
	FieldOciImageRef = "oci_image_ref"
	// FieldOciDigest holds the string denoting the oci_digest field in the database.
	FieldOciDigest = "oci_digest"
	// FieldReadmeHTML holds the string denoting the readme_html field in the database.
	FieldReadmeHTML = "readme_html"
	// FieldManifestJSON holds the string denoting the manifest_json field in the database.
	FieldManifestJSON = "manifest_json"
	// EdgePlugin holds the string denoting the plugin edge name in mutations.
	EdgePlugin = "plugin"
	// Table holds the table name of the pluginversion in the database.
	Table = "plugin_versions"
	// PluginTable is the table that holds the plugin relation/edge.
	PluginTable = "plugin_versions"
	// PluginInverseTable is the table name for the Plugin entity.
	// It exists in this package in order to avoid circular dependency with the "plugin" package.
	PluginInverseTable = "plugins"
	// PluginColumn is the table column denoting the plugin relation/edge.
	PluginColumn = "plugin_id"
)

// Columns holds all SQL columns for pluginversion fields.
var Columns = []string{
	FieldID,
	FieldPluginID,
	FieldVersion,
	FieldOciImageRef,
	FieldOciDigest,
	FieldReadmeHTML,
	FieldManifestJSON,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// DefaultOciImageRef holds the default value on creation for the "oci_image_ref" field.
	DefaultOciImageRef string
	// OciDigestValidator is a validator for the "oci_digest" field. It is called by the builders before save.
	OciDigestValidator func(string) error
	// DefaultReadmeHTML holds the default value on creation for the "readme_html" field.
	DefaultReadmeHTML string
	// DefaultManifestJSON holds the default value on creation for the "manifest_json" field.
	DefaultManifestJSON map[string]interface{}
)

// OrderOption defines the ordering options for the PluginVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPluginID orders the results by the plugin_id field.
func ByPluginID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByOciImageRef orders the results by the oci_image_ref field.
func ByOciImageRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOciImageRef, opts...).ToFunc()
}

// ByOciDigest orders the results by the oci_digest field.
func ByOciDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOciDigest, opts...).ToFunc()
}

// ByReadmeHTML orders the results by the readme_html field.
func ByReadmeHTML(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadmeHTML, opts...).ToFunc()
}

// ByPluginField orders the results by plugin field.
func ByPluginField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPluginStep(), sql.OrderByField(field, opts...))
	}
}
func newPluginStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PluginInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PluginTable, PluginColumn),
	)
}
