// Code generated by ent, DO NOT EDIT.

package pluginversion

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/flowline-io/flowbot-registry/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLTE(FieldID, id))
}

// PluginID applies equality check predicate on the "plugin_id" field. It's identical to PluginIDEQ.
func PluginID(v int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldPluginID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldVersion, v))
}

// OciImageRef applies equality check predicate on the "oci_image_ref" field. It's identical to OciImageRefEQ.
func OciImageRef(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldOciImageRef, v))
}

// OciDigest applies equality check predicate on the "oci_digest" field. It's identical to OciDigestEQ.
func OciDigest(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldOciDigest, v))
}

// ReadmeHTML applies equality check predicate on the "readme_html" field. It's identical to ReadmeHTMLEQ.
func ReadmeHTML(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldReadmeHTML, v))
}

// PluginIDEQ applies the EQ predicate on the "plugin_id" field.
func PluginIDEQ(v int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldPluginID, v))
}

// PluginIDNEQ applies the NEQ predicate on the "plugin_id" field.
func PluginIDNEQ(v int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNEQ(FieldPluginID, v))
}

// PluginIDIn applies the In predicate on the "plugin_id" field.
func PluginIDIn(vs ...int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldIn(FieldPluginID, vs...))
}

// PluginIDNotIn applies the NotIn predicate on the "plugin_id" field.
func PluginIDNotIn(vs ...int) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNotIn(FieldPluginID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldContainsFold(FieldVersion, v))
}

// OciImageRefEQ applies the EQ predicate on the "oci_image_ref" field.
func OciImageRefEQ(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldOciImageRef, v))
}

// OciImageRefNEQ applies the NEQ predicate on the "oci_image_ref" field.
func OciImageRefNEQ(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNEQ(FieldOciImageRef, v))
}

// OciImageRefIn applies the In predicate on the "oci_image_ref" field.
func OciImageRefIn(vs ...string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldIn(FieldOciImageRef, vs...))
}

// OciImageRefNotIn applies the NotIn predicate on the "oci_image_ref" field.
func OciImageRefNotIn(vs ...string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNotIn(FieldOciImageRef, vs...))
}

// OciImageRefGT applies the GT predicate on the "oci_image_ref" field.
func OciImageRefGT(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGT(FieldOciImageRef, v))
}

// OciImageRefGTE applies the GTE predicate on the "oci_image_ref" field.
func OciImageRefGTE(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGTE(FieldOciImageRef, v))
}

// OciImageRefLT applies the LT predicate on the "oci_image_ref" field.
func OciImageRefLT(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLT(FieldOciImageRef, v))
}

// OciImageRefLTE applies the LTE predicate on the "oci_image_ref" field.
func OciImageRefLTE(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLTE(FieldOciImageRef, v))
}

// OciImageRefContains applies the Contains predicate on the "oci_image_ref" field.
func OciImageRefContains(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldContains(FieldOciImageRef, v))
}

// OciImageRefHasPrefix applies the HasPrefix predicate on the "oci_image_ref" field.
func OciImageRefHasPrefix(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldHasPrefix(FieldOciImageRef, v))
}

// OciImageRefHasSuffix applies the HasSuffix predicate on the "oci_image_ref" field.
func OciImageRefHasSuffix(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldHasSuffix(FieldOciImageRef, v))
}

// OciImageRefEqualFold applies the EqualFold predicate on the "oci_image_ref" field.
func OciImageRefEqualFold(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEqualFold(FieldOciImageRef, v))
}

// OciImageRefContainsFold applies the ContainsFold predicate on the "oci_image_ref" field.
func OciImageRefContainsFold(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldContainsFold(FieldOciImageRef, v))
}

// OciDigestEQ applies the EQ predicate on the "oci_digest" field.
func OciDigestEQ(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldOciDigest, v))
}

// OciDigestNEQ applies the NEQ predicate on the "oci_digest" field.
func OciDigestNEQ(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNEQ(FieldOciDigest, v))
}

// OciDigestIn applies the In predicate on the "oci_digest" field.
func OciDigestIn(vs ...string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldIn(FieldOciDigest, vs...))
}

// OciDigestNotIn applies the NotIn predicate on the "oci_digest" field.
func OciDigestNotIn(vs ...string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNotIn(FieldOciDigest, vs...))
}

// OciDigestGT applies the GT predicate on the "oci_digest" field.
func OciDigestGT(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGT(FieldOciDigest, v))
}

// OciDigestGTE applies the GTE predicate on the "oci_digest" field.
func OciDigestGTE(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGTE(FieldOciDigest, v))
}

// OciDigestLT applies the LT predicate on the "oci_digest" field.
func OciDigestLT(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLT(FieldOciDigest, v))
}

// OciDigestLTE applies the LTE predicate on the "oci_digest" field.
func OciDigestLTE(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLTE(FieldOciDigest, v))
}

// OciDigestContains applies the Contains predicate on the "oci_digest" field.
func OciDigestContains(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldContains(FieldOciDigest, v))
}

// OciDigestHasPrefix applies the HasPrefix predicate on the "oci_digest" field.
func OciDigestHasPrefix(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldHasPrefix(FieldOciDigest, v))
}

// OciDigestHasSuffix applies the HasSuffix predicate on the "oci_digest" field.
func OciDigestHasSuffix(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldHasSuffix(FieldOciDigest, v))
}

// OciDigestEqualFold applies the EqualFold predicate on the "oci_digest" field.
func OciDigestEqualFold(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEqualFold(FieldOciDigest, v))
}

// OciDigestContainsFold applies the ContainsFold predicate on the "oci_digest" field.
func OciDigestContainsFold(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldContainsFold(FieldOciDigest, v))
}

// ReadmeHTMLEQ applies the EQ predicate on the "readme_html" field.
func ReadmeHTMLEQ(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEQ(FieldReadmeHTML, v))
}

// ReadmeHTMLNEQ applies the NEQ predicate on the "readme_html" field.
func ReadmeHTMLNEQ(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNEQ(FieldReadmeHTML, v))
}

// ReadmeHTMLIn applies the In predicate on the "readme_html" field.
func ReadmeHTMLIn(vs ...string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldIn(FieldReadmeHTML, vs...))
}

// ReadmeHTMLNotIn applies the NotIn predicate on the "readme_html" field.
func ReadmeHTMLNotIn(vs ...string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldNotIn(FieldReadmeHTML, vs...))
}

// ReadmeHTMLGT applies the GT predicate on the "readme_html" field.
func ReadmeHTMLGT(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGT(FieldReadmeHTML, v))
}

// ReadmeHTMLGTE applies the GTE predicate on the "readme_html" field.
func ReadmeHTMLGTE(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldGTE(FieldReadmeHTML, v))
}

// ReadmeHTMLLT applies the LT predicate on the "readme_html" field.
func ReadmeHTMLLT(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLT(FieldReadmeHTML, v))
}

// ReadmeHTMLLTE applies the LTE predicate on the "readme_html" field.
func ReadmeHTMLLTE(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldLTE(FieldReadmeHTML, v))
}

// ReadmeHTMLContains applies the Contains predicate on the "readme_html" field.
func ReadmeHTMLContains(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldContains(FieldReadmeHTML, v))
}

// ReadmeHTMLHasPrefix applies the HasPrefix predicate on the "readme_html" field.
func ReadmeHTMLHasPrefix(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldHasPrefix(FieldReadmeHTML, v))
}

// ReadmeHTMLHasSuffix applies the HasSuffix predicate on the "readme_html" field.
func ReadmeHTMLHasSuffix(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldHasSuffix(FieldReadmeHTML, v))
}

// ReadmeHTMLEqualFold applies the EqualFold predicate on the "readme_html" field.
func ReadmeHTMLEqualFold(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldEqualFold(FieldReadmeHTML, v))
}

// ReadmeHTMLContainsFold applies the ContainsFold predicate on the "readme_html" field.
func ReadmeHTMLContainsFold(v string) predicate.PluginVersion {
	return predicate.PluginVersion(sql.FieldContainsFold(FieldReadmeHTML, v))
}

// HasPlugin applies the HasEdge predicate on the "plugin" edge.
func HasPlugin() predicate.PluginVersion {
	return predicate.PluginVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PluginTable, PluginColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPluginWith applies the HasEdge predicate on the "plugin" edge with a given conditions (other predicates).
func HasPluginWith(preds ...predicate.Plugin) predicate.PluginVersion {
	return predicate.PluginVersion(func(s *sql.Selector) {
		step := newPluginStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PluginVersion) predicate.PluginVersion {
	return predicate.PluginVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PluginVersion) predicate.PluginVersion {
	return predicate.PluginVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PluginVersion) predicate.PluginVersion {
	return predicate.PluginVersion(sql.NotPredicates(p))
}
